# Site settings
title: Almost Surely
email: felix@jung.fm
description: "Personal webpage of Felix Jung."
url: "http://felixjung.io"
twitter_username: feju
github_username:  feju
timezone: Europe/Berlin
encoding: utf-8

# Pagination
paginate: 8

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

# Code Highlighting
highlighter: pygments

# Setup pages
relative_permalinks: false

# Exclusions
exclude: [_assets, _bower, node_modules, Gruntfile.js, bower.json, package.json, Gemfile]
