# Site settings
title: felixjung.io
email: felix@jung.fm
description: "Personal webpage of Felix Jung."
url: "http://felixjung.io"
twitter_username: feju
github_username:  felixjung
timezone: Europe/Berlin
encoding: utf-8

# Github pages
safe: true
lsi: false

# Additional variable for RSS
name: felixjung.io

# Pagination
paginate: 8

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

# Code Highlighting
# highlighter: rouge

# Setup pages
relative_permalinks: false

# Collections
collections:
  - projects

# Exclusions
exclude: [node_modules, Gruntfile.js, bower.json, package.json, Gemfile, Gemfile.lock, Readme.md]

# Plugins
gems:
- jekyll-mentions
- jemoji
# - jekyll-redirect-from
# - jekyll-sitemap
