# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: felixjung.io
email: jung.felix@gmail.com
description: >
  Felix Jung is a Berlin based web developer. He currently works as frontend engineer at mPOS provider SumUp.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://felixjung.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: "@feju"
github_username:  "felix.jung"
author_name: "Felix Jung"
favicon: "favicon.png"
preview_image: "preview-image.jpg"

# Paths
assets_path: "assets"
image_folder: "images"
meta_folder: "meta"
css_file: "styles.css"
js_file: "main.js"

# Build settings
markdown: kramdown
sass:
  sass_dir:          _sass
  style:            :compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - _svgs
  - _build
  - node_modules
  - vendor
