# Site settings
title: felixjung.io
email: felix@jung.fm
description: "Personal webpage of Felix Jung."
url: "http://felixjung.io"
twitter_username: feju
github_username: felixjung
timezone: Europe/Berlin
encoding: utf-8

# Github pages
lsi: false

# Additional variable for RSS
name: felixjung.io

# Pagination
paginate: 8

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Setup pages
relative_permalinks: false

# Collections
collections:
  - projects

# Exclusions
exclude: [Readme.md]
