- name: github
  url: http://github.com/felixjung
  alt: "Check out my code on Github"
- name: medium
  url: http://medium.com/felix-jung
  alt: "Read my blog on Medium"
- name: twitter
  url: http://twitter.com/feju
  alt: "Visit @feju on Twitter"
- name: instagram
  url: http://instagram.com/felixjung
  alt: "Some photos end up on Instagram"
