- name: github
  url: https://github.com/felixjung
  alt: "Check out my code on Github"
- name: medium
  url: https://codematters.blog
  alt: "Read my blog on Medium"
- name: twitter
  url: https://twitter.com/feju
  alt: "Visit @feju on Twitter"
- name: instagram
  url: https://instagram.com/felixjung
  alt: "Some photos end up on Instagram"
